# Build stage
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /api cmd/api/main.go

# Run stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /api /api
COPY .env .env
EXPOSE 8080
CMD ["/api"]
